# Generated by Django 6.0 on 2025-12-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='diary/picture/', verbose_name='写真'),
        ),
    ]
